/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUpload_fileRouteImport } from './routes/_app/upload_file'
import { Route as AppTableRouteImport } from './routes/_app/table'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppDragAndDropRouteImport } from './routes/_app/drag-and-drop'
import { Route as AppLocalRegistryRealtyRouteImport } from './routes/_app/local-registry/realty'
import { Route as AppLocalRegistryLandRouteImport } from './routes/_app/local-registry/land'
import { Route as AppGlobalRegistryRealtyRouteImport } from './routes/_app/global-registry/realty'
import { Route as AppGlobalRegistryLandRouteImport } from './routes/_app/global-registry/land'
import { Route as AppDiffRealtyRouteImport } from './routes/_app/diff/realty'
import { Route as AppDiffLandRouteImport } from './routes/_app/diff/land'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUpload_fileRoute = AppUpload_fileRouteImport.update({
  id: '/upload_file',
  path: '/upload_file',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTableRoute = AppTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDragAndDropRoute = AppDragAndDropRouteImport.update({
  id: '/drag-and-drop',
  path: '/drag-and-drop',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocalRegistryRealtyRoute = AppLocalRegistryRealtyRouteImport.update({
  id: '/local-registry/realty',
  path: '/local-registry/realty',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocalRegistryLandRoute = AppLocalRegistryLandRouteImport.update({
  id: '/local-registry/land',
  path: '/local-registry/land',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGlobalRegistryRealtyRoute = AppGlobalRegistryRealtyRouteImport.update({
  id: '/global-registry/realty',
  path: '/global-registry/realty',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGlobalRegistryLandRoute = AppGlobalRegistryLandRouteImport.update({
  id: '/global-registry/land',
  path: '/global-registry/land',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiffRealtyRoute = AppDiffRealtyRouteImport.update({
  id: '/diff/realty',
  path: '/diff/realty',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiffLandRoute = AppDiffLandRouteImport.update({
  id: '/diff/land',
  path: '/diff/land',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/drag-and-drop': typeof AppDragAndDropRoute
  '/requests': typeof AppRequestsRoute
  '/table': typeof AppTableRoute
  '/upload_file': typeof AppUpload_fileRoute
  '/diff/land': typeof AppDiffLandRoute
  '/diff/realty': typeof AppDiffRealtyRoute
  '/global-registry/land': typeof AppGlobalRegistryLandRoute
  '/global-registry/realty': typeof AppGlobalRegistryRealtyRoute
  '/local-registry/land': typeof AppLocalRegistryLandRoute
  '/local-registry/realty': typeof AppLocalRegistryRealtyRoute
}
export interface FileRoutesByTo {
  '/drag-and-drop': typeof AppDragAndDropRoute
  '/requests': typeof AppRequestsRoute
  '/table': typeof AppTableRoute
  '/upload_file': typeof AppUpload_fileRoute
  '/': typeof AppIndexRoute
  '/diff/land': typeof AppDiffLandRoute
  '/diff/realty': typeof AppDiffRealtyRoute
  '/global-registry/land': typeof AppGlobalRegistryLandRoute
  '/global-registry/realty': typeof AppGlobalRegistryRealtyRoute
  '/local-registry/land': typeof AppLocalRegistryLandRoute
  '/local-registry/realty': typeof AppLocalRegistryRealtyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/drag-and-drop': typeof AppDragAndDropRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/table': typeof AppTableRoute
  '/_app/upload_file': typeof AppUpload_fileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/diff/land': typeof AppDiffLandRoute
  '/_app/diff/realty': typeof AppDiffRealtyRoute
  '/_app/global-registry/land': typeof AppGlobalRegistryLandRoute
  '/_app/global-registry/realty': typeof AppGlobalRegistryRealtyRoute
  '/_app/local-registry/land': typeof AppLocalRegistryLandRoute
  '/_app/local-registry/realty': typeof AppLocalRegistryRealtyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drag-and-drop'
    | '/requests'
    | '/table'
    | '/upload_file'
    | '/diff/land'
    | '/diff/realty'
    | '/global-registry/land'
    | '/global-registry/realty'
    | '/local-registry/land'
    | '/local-registry/realty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/drag-and-drop'
    | '/requests'
    | '/table'
    | '/upload_file'
    | '/'
    | '/diff/land'
    | '/diff/realty'
    | '/global-registry/land'
    | '/global-registry/realty'
    | '/local-registry/land'
    | '/local-registry/realty'
  id:
    | '__root__'
    | '/_app'
    | '/_app/drag-and-drop'
    | '/_app/requests'
    | '/_app/table'
    | '/_app/upload_file'
    | '/_app/'
    | '/_app/diff/land'
    | '/_app/diff/realty'
    | '/_app/global-registry/land'
    | '/_app/global-registry/realty'
    | '/_app/local-registry/land'
    | '/_app/local-registry/realty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/upload_file': {
      id: '/_app/upload_file'
      path: '/upload_file'
      fullPath: '/upload_file'
      preLoaderRoute: typeof AppUpload_fileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/table': {
      id: '/_app/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AppTableRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/drag-and-drop': {
      id: '/_app/drag-and-drop'
      path: '/drag-and-drop'
      fullPath: '/drag-and-drop'
      preLoaderRoute: typeof AppDragAndDropRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/local-registry/realty': {
      id: '/_app/local-registry/realty'
      path: '/local-registry/realty'
      fullPath: '/local-registry/realty'
      preLoaderRoute: typeof AppLocalRegistryRealtyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/local-registry/land': {
      id: '/_app/local-registry/land'
      path: '/local-registry/land'
      fullPath: '/local-registry/land'
      preLoaderRoute: typeof AppLocalRegistryLandRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/global-registry/realty': {
      id: '/_app/global-registry/realty'
      path: '/global-registry/realty'
      fullPath: '/global-registry/realty'
      preLoaderRoute: typeof AppGlobalRegistryRealtyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/global-registry/land': {
      id: '/_app/global-registry/land'
      path: '/global-registry/land'
      fullPath: '/global-registry/land'
      preLoaderRoute: typeof AppGlobalRegistryLandRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/diff/realty': {
      id: '/_app/diff/realty'
      path: '/diff/realty'
      fullPath: '/diff/realty'
      preLoaderRoute: typeof AppDiffRealtyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/diff/land': {
      id: '/_app/diff/land'
      path: '/diff/land'
      fullPath: '/diff/land'
      preLoaderRoute: typeof AppDiffLandRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDragAndDropRoute: typeof AppDragAndDropRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppTableRoute: typeof AppTableRoute
  AppUpload_fileRoute: typeof AppUpload_fileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDiffLandRoute: typeof AppDiffLandRoute
  AppDiffRealtyRoute: typeof AppDiffRealtyRoute
  AppGlobalRegistryLandRoute: typeof AppGlobalRegistryLandRoute
  AppGlobalRegistryRealtyRoute: typeof AppGlobalRegistryRealtyRoute
  AppLocalRegistryLandRoute: typeof AppLocalRegistryLandRoute
  AppLocalRegistryRealtyRoute: typeof AppLocalRegistryRealtyRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDragAndDropRoute: AppDragAndDropRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppTableRoute: AppTableRoute,
  AppUpload_fileRoute: AppUpload_fileRoute,
  AppIndexRoute: AppIndexRoute,
  AppDiffLandRoute: AppDiffLandRoute,
  AppDiffRealtyRoute: AppDiffRealtyRoute,
  AppGlobalRegistryLandRoute: AppGlobalRegistryLandRoute,
  AppGlobalRegistryRealtyRoute: AppGlobalRegistryRealtyRoute,
  AppLocalRegistryLandRoute: AppLocalRegistryLandRoute,
  AppLocalRegistryRealtyRoute: AppLocalRegistryRealtyRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
