/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUpload_fileRouteImport } from './routes/_app/upload_file'
import { Route as AppTableRouteImport } from './routes/_app/table'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppDragAndDropRouteImport } from './routes/_app/drag-and-drop'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUpload_fileRoute = AppUpload_fileRouteImport.update({
  id: '/upload_file',
  path: '/upload_file',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTableRoute = AppTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDragAndDropRoute = AppDragAndDropRouteImport.update({
  id: '/drag-and-drop',
  path: '/drag-and-drop',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/drag-and-drop': typeof AppDragAndDropRoute
  '/requests': typeof AppRequestsRoute
  '/table': typeof AppTableRoute
  '/upload_file': typeof AppUpload_fileRoute
}
export interface FileRoutesByTo {
  '/drag-and-drop': typeof AppDragAndDropRoute
  '/requests': typeof AppRequestsRoute
  '/table': typeof AppTableRoute
  '/upload_file': typeof AppUpload_fileRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/drag-and-drop': typeof AppDragAndDropRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/table': typeof AppTableRoute
  '/_app/upload_file': typeof AppUpload_fileRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/drag-and-drop' | '/requests' | '/table' | '/upload_file'
  fileRoutesByTo: FileRoutesByTo
  to: '/drag-and-drop' | '/requests' | '/table' | '/upload_file' | '/'
  id: '__root__' | '/_app' | '/_app/drag-and-drop' | '/_app/requests' | '/_app/table' | '/_app/upload_file' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/upload_file': {
      id: '/_app/upload_file'
      path: '/upload_file'
      fullPath: '/upload_file'
      preLoaderRoute: typeof AppUpload_fileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/table': {
      id: '/_app/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof AppTableRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/drag-and-drop': {
      id: '/_app/drag-and-drop'
      path: '/drag-and-drop'
      fullPath: '/drag-and-drop'
      preLoaderRoute: typeof AppDragAndDropRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDragAndDropRoute: typeof AppDragAndDropRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppTableRoute: typeof AppTableRoute
  AppUpload_fileRoute: typeof AppUpload_fileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDragAndDropRoute: AppDragAndDropRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppTableRoute: AppTableRoute,
  AppUpload_fileRoute: AppUpload_fileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(AppRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
